INSERT INTO Equipement VALUES ( 1,'Atom','ATOM',10); 
INSERT INTO Equipement VALUES ( 2,'Ordie','ORDIN',10); 
INSERT INTO Equipement VALUES ( 3,'Cat','CAT',10); 
INSERT INTO Equipement VALUES ( 4,'ptwe','APTWE',10); 
INSERT INTO Equipement VALUES ( 5,'Volmet','VOLMET',10); 
INSERT INTO Equipement VALUES ( 6,'Sioma','SIOMA',10); 

//ATOM
INSERT INTO SousEnsemble VALUES (1,1,'ANERRCK1ARK','BAIE N°1','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (2,1,'ANERFDP1ALI','FDP/ AGDP','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (3,1,'ANERREC1ALI','REC','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (4,1,'ANERRTP1ALI','MEDISIS','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (5,1,'ANERFPC1ALI','FPCF/ SNMAP/ SAP','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (6,1,'ANERRTR2ARO','ROUTEUR SITA','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (7,1,'ANERRTR1ARO','ROUTEUR ADS','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (8,1,'ANERNTP1ANS','HORLOGE','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (9,1,'ANERNET01SW','LAN S','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (10,1,'ANERNET1ASW','LAN A','STR - SALLE TECHNIQUE'); 

INSERT INTO SousEnsemble VALUES (11,1,'ANERRCK1BRK','BAIE N°2','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (12,1,'ANERFDP1BLI','FDP/ AGDP','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (13,1,'ANERREC1BLI','REC','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (14,1,'ANERRTP1BLI','MEDISIS','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (15,1,'ANERFPC1BLI','FPCF/ SNMAP/ SAP','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (16,1,'ANERRTR2BRO','ROUTEUR SITA','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (17,1,'ANERRTR1BRO','ROUTEUR ADS','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (18,1,'ANERNTP1BNS','HORLOGE','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (19,1,'ANERSUP01RO','LAN S','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (20,1,'ANERNET1BSW','LAN A','STR - SALLE TECHNIQUE'); 


INSERT INTO SousEnsemble VALUES (21,1,'ANERRCK1RK','BAIE N°3','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (22,1,'ANERFDP1LI','RBP/ MTP','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (23,1,'PTNR083','ROUTEUR SITA','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (24,1,'ANERXRA01RO','ROUTEUR INTERNET','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (25,1,'MEDIA CONVERTER','MEDIA CONVERTER voie A','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (26,1,'MEDIA CONVERTER','MEDIA CONVERTER voie B','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (27,1,'MEDIA CONVERTER','MEDIA CONVERTER RCMS','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (28,1,'BLACKBOX CONVERTER','BLACKBOX CONVERTER','STR - SALLE TECHNIQUE'); 

INSERT INTO SousEnsemble VALUES (29,1,'ANTSRCK01RK','BAIE N°4','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (30,1,'ANTSEXE03LI','MEDISIS/ ATG','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (31,1,'ANTSEXE01LI','FDP/ AGDP/ SNMAP','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (32,1,'ANTSEXE02LI','REC/ ASPB/ FPCF/ SAP','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (33,1,'LOGISTIQUE_06','SPARE','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (34,1,'ANTSRTR02RO','ROUTEUR BACKUP','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (35,1,'ANERNTP01NS','HORLOGE','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (36,1,'ANTSNET01SW','LAN S','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (37,1,'ANTSNET1BSW','LAN B','STR - SALLE TECHNIQUE'); 
INSERT INTO SousEnsemble VALUES (38,1,'ANTSNET1ASW','LAN A','STR - SALLE TECHNIQUE'); 

INSERT INTO SousEnsemble VALUES (39,1,'ANERTKS01LI','EN-ROUTE','STR - SALLE SUPERVISION'); 
INSERT INTO SousEnsemble VALUES (40,1,'ANEROPS01LI','','STR - CRNA'); 
INSERT INTO SousEnsemble VALUES (41,1,'ANERFDO01LI','','STR - CRNA'); 
INSERT INTO SousEnsemble VALUES (42,1,'ANEREXC01LI','','STR - CRNA/ MEUBLE 1'); 
INSERT INTO SousEnsemble VALUES (43,1,'ANEREXC02LI','','STR - CRNA/ MEUBLE 2'); 
INSERT INTO SousEnsemble VALUES (44,1,'ANERPLC01LI','','STR - CRNA/ MEUBLE 1'); 
INSERT INTO SousEnsemble VALUES (45,1,'ANERPLC02LI','','STR - CRNA/ MEUBLE 2'); 
INSERT INTO SousEnsemble VALUES (46,1,'ANERDBM01LI','','STR - CRNA'); 
INSERT INTO SousEnsemble VALUES (47,1,'ANERTWG01LI','','BT - VIGIE NA'); 
INSERT INTO SousEnsemble VALUES (48,1,'ANERTWR01LI','','BT - VIGIE NA'); 
INSERT INTO SousEnsemble VALUES (49,1,'ANERTWP01LI','','BT - VIGIE NA'); 


//ORDIN
INSERT INTO SousEnsemble VALUES (50,2,'PC DE BUREAU','PC REP','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (51,2,'','PC SECREP','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (52,2,'','PC CADRE PERSONNEL','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (53,2,'','PC CAF','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (54,2,'','PC SEC/CAF','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (55,2,'','PC CU BUDGET','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (56,2,'','PC CU PERSONNEL','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (57,2,'','PC CADRE SOLDE','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (58,2,'','PC CADRE AFF. SOC','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (59,2,'','PC COURRIER','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (60,2,'','PC CADRE RECETTE','REPRESENTATION 1° ET.'); 

INSERT INTO SousEnsemble VALUES (70,2,'','PC CU/ RECETTES','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (71,2,'','PC CU SQE','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (72,2,'','PC CU BUDGET PC CAISSE','REPRESENTATION 1° ET.'); 
INSERT INTO SousEnsemble VALUES (73,2,'','PC CAISSE','REPRESENTATION RDC'); 
INSERT INTO SousEnsemble VALUES (74,2,'','PC SEC/PAIERIE','REPRESENTATION RDC'); 
INSERT INTO SousEnsemble VALUES (75,2,'','PC PAYEUR','REPRESENTATION RDC'); 
INSERT INTO SousEnsemble VALUES (76,2,'','PC CSSQE. SOC','BT - VIGIE NA'); 
INSERT INTO SousEnsemble VALUES (77,2,'','PC CU COMPTA GENE','REPRESENTATION RDC'); 
INSERT INTO SousEnsemble VALUES (78,2,'','PC CADRE RECETTE','REPRESENTATION RDC'); 
INSERT INTO SousEnsemble VALUES (79,2,'','PC CADRE DEPENSE ','REPRESENTATION RDC');


INSERT INTO SousEnsemble VALUES (80,2,'','PC CU CA','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (81,2,'','PC CU OPS ATC','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (82,2,'','PC CU QIP/NA ','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (83,2,'','PC CU QIP IRE','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (84,2,'','PC CELICA 1','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (85,2,'','PC CELICA 2','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (86,2,'','PC CELICA 3','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (87,2,'','PC CELICA 4','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (88,2,'','PC CELICA 5','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (89,2,'','PC CELICA 6','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (90,2,'','PC CELICA 7','STR - 1° ETAGE'); 
INSERT INTO SousEnsemble VALUES (91,2,'','PC STR','STR - RDC'); 
INSERT INTO SousEnsemble VALUES (92,2,'','PC CADRE CNS','STR - RDC'); 
INSERT INTO SousEnsemble VALUES (93,2,'','PC CU CNS','STR - RDC'); 

INSERT INTO SousEnsemble VALUES (94,2,'','PC C/ MIGC','BATIMENT IGC');
INSERT INTO SousEnsemble VALUES (95,2,'','PC SECIGC','BATIMENT IGC');
INSERT INTO SousEnsemble VALUES (96,2,'','PC CU/ PV','BATIMENT IGC');
INSERT INTO SousEnsemble VALUES (97,2,'','PC CU/ PATRIMOINES','BATIMENT IGC');
INSERT INTO SousEnsemble VALUES (98,2,'','PC CU/ GARAGE','BATIMENT IGC');

INSERT INTO SousEnsemble VALUES (99,2,'','PC IL (BIA)','BT RC');
INSERT INTO SousEnsemble VALUES (100,2,'','PC AL (BDP)','BT RC');
INSERT INTO SousEnsemble VALUES (101,2,'','PC FACTURATION 1','BT RC');
INSERT INTO SousEnsemble VALUES (102,2,'','PC FACTURATION 2','BT RC');
INSERT INTO SousEnsemble VALUES (103,2,'','PC CU FACTURATION','BT RC');
INSERT INTO SousEnsemble VALUES (104,2,'','PC CU AIM','BT RC');
INSERT INTO SousEnsemble VALUES (105,2,'','PC CADRE AIM','BT RC');
INSERT INTO SousEnsemble VALUES (106,2,'','PC CU PREVI/PROTEC','BT RC');
INSERT INTO SousEnsemble VALUES (107,2,'','PC SYNERGIE','BT RC');
INSERT INTO SousEnsemble VALUES (108,2,'','PC PREVI','BT RC');
INSERT INTO SousEnsemble VALUES (109,2,'','PC CU BNI','BT RC');
INSERT INTO SousEnsemble VALUES (110,2,'','PC BNI','BT RC');
INSERT INTO SousEnsemble VALUES (111,2,'','PC STANDARD','BT RC');



//CAT
INSERT INTO SousEnsemble VALUES (114,3,'BAIE AMHS','BAIE AMHS','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (115,3,'SERVEUR CN1','SERVEUR CN1-MHS','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (116,3,'SERVEUR CN2','SERVEUR CN2-MHS','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (117,3,'SERVEUR CN3','SERVEUR CN3-AIS','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (118,3,'SERVEUR CN4','SERVEUR CN4-AIS','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (119,3,'SERVEUR MOBA','SERVEUR MOBA','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (120,3,'TAPE LIBRARY','TAPE LIBRARY','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (121,3,'FIREWALL','FIREWALL','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (122,3,'TIROIR KVM','TIROIR KVM','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (123,3,'A/B SWITCH','A/B SWITCH','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (124,3,'TERMINAL SERVER','','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (125,3,'TERMINAL SERVER','','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (126,3,'FARLINX','TERMINAL SERVER 1','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (127,3,'FARLINX','TERMINAL SERVER 2','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (128,3,'SWITCH','FARLINX 1','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (129,3,'SWITCH','FARLINX 2','STR - SALLE TECH.');
INSERT INTO SousEnsemble VALUES (130,3,'ROUTEUR','SWITCH 1','STR - SALLE TECH.');



//APTWE

INSERT INTO SousEnsemble VALUES (131,4,'PC MSG-1','MSG','SALLE TECH. STR');
INSERT INTO SousEnsemble VALUES (132,4,'PC MSG-2','MSG','SALLE VMA BT');
INSERT INTO SousEnsemble VALUES (133,4,'ANTENNE PARABOLIQUE','MSG','COURS REPRESENTATION');
INSERT INTO SousEnsemble VALUES (134,4,'PC SADIS','MSG','SALLE VMA BT');

//VOLMET

INSERT INTO SousEnsemble VALUES (135,5,'SERVEUR 2 VOLMET','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (136,5,'KVM VOLMET','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (137,5,'VOICE SERVEUR 1 ','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (138,5,'VOICE SERVEUR 2','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (139,5,'PC SUPERVISION HF VOLMET CAT','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (140,5,'PC VOLMET CAT','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (141,5,'PC VOLMET PREVI','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (142,5,'PC SUPERVISION HF VOLMET STR','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (143,5,'SWITCH 1 VOLMET','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (144,5,'SWITCH 2 VOLMET','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (145,5,'ROUTEUR 1 VOLMET','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (146,5,'ROUTEUR 2 VOLMET','','BLOC TECH.1ER ET.');


//SIOMA

INSERT INTO SousEnsemble VALUES (147,6,'SERVEUR CAOBSCHROME 1','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (148,6,'SERVEUR CAOBSCHROME 2','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (149,6,'KVM','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (150,6,'WORKSTATION MAINTENANCE','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (151,6,'WORKSTATION PREVI','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (152,6,'WORKSTATION VMA','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (153,6,'POSTE DE VISUALISATION TWR','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (154,6,'VISUCHROME TWR','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (155,6,'COFFRET BALISAGE','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (156,6,'CAPTEUR PRESSION PTB330 VMA','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (157,6,'TELEMETRE DE NUAGE','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (158,6,'CAPTEUR DE FOUDRE','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (159,6,'CAPTEUR VENT WS200','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (160,6,'CAPTEUR TEMP','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (161,6,'TRANSMISSOMETRE/LUMINANCEMETRE','','BLOC TECH.1ER ET.');
INSERT INTO SousEnsemble VALUES (162,6,'TRANSMISSOMETRE/LUMINANCEMETRE','','BLOC TECH.1ER ET.');


















































































